### ISSUE TITLE
Calls to the database hang without exit

### ISSUE THREAD

**Issue by francojc** [TalkBank/TBDBr#1]
Calls to the Talkbank DB hang. 

`example_utterances <- getUtterances(corpusName = 'childes',  corpora = c('childes', 'Eng-NA', 'MacWhinney', '010411a'));`

Returns

`"Fetching data, please wait..."`

The call does not complete (returning data) and does not exit.

I'm using version 0.1.0 of `TBDBr`. 

R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.5.1

**Comment by rbcavanaugh** [comment]
Unfortunately, I'm not able to reproduce the error. Could you try running the randomTests() function (which runs a series of test queries) and see if you continue to have trouble accessing the database?

**Comment by francojc** [comment]
I ran `randomTests()` and all good. So I then re-ran the example `getUtterances()` call and no problem. So I'm not sure what changed (possibly the WIFI network I was on previously), but I'm good now.

Thanks.
