### ISSUE TITLE
Issue with `kable()` after loading TBDBr

### ISSUE THREAD

**Issue by francojc** [TalkBank/TBDBr#2]
I'm having an issue with table output once I load the `TBDBr` package in my Quarto document. 

Here's a reproducible example of my `.qmd` document with the rendered tables.

---

```
---
title: "Test document"
format: html
---
```

Load in the basic packages. 
````
```{r}
#| label: setup
#| message: false
library(tidyverse)
library(knitr)
```
````

Create a table using `kable()`. 

````
```{r}
#| label: tbl-test-1
#| tbl-cap: 'Good table.'

iris |> 
  slice_head(n = 10) |> 
  kable()
```
````

<img width="712" alt="Screen Shot 2022-10-18 at 9 58 28 AM" src="https://user-images.githubusercontent.com/1140826/196450934-dd2390ae-55eb-4c1d-a629-3569814c70f0.png">

Load the `TBDBr` package and then run the same code as above to generate a table using `kable()`. 

````
```{r}
#| label: tbl-test-2
#| tab-cap: 'Bad table.'

library(TBDBr)

iris |> 
  slice_head(n = 10) |> 
  kable()
```
````

<img width="700" alt="Screen Shot 2022-10-18 at 9 58 39 AM" src="https://user-images.githubusercontent.com/1140826/196451108-697b4754-e9c4-4085-b0c5-cbeec9276fe2.png">

---

I suspect that it may have something to do with `kableExtra` being loaded as a dependency.  

Here's my session info if it is of any help. 

```
─ Session info 

 version  R version 4.1.2 (2021-11-01)
 os       macOS Monterey 12.6
 system   x86_64, darwin17.0
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/New_York
 date     2022-10-18
 rstudio  2022.07.1+554 Spotted Wakerobin (desktop)
 pandoc   2.19.2 @ /usr/local/bin/ (via markdown)


─ Packages 

 package   * version date (UTC) lib source
 dplyr     * 1.0.10  2022-09-01 [1] CRAN (R 4.1.2)
 forcats   * 0.5.2   2022-08-19 [1] CRAN (R 4.1.2)
 ggplot2   * 3.3.6   2022-05-03 [1] CRAN (R 4.1.2)
 knitr     * 1.40    2022-08-24 [1] CRAN (R 4.1.2)
 purrr     * 0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
 readr     * 2.1.3   2022-10-01 [1] CRAN (R 4.1.2)
 shiny     * 1.7.2   2022-07-19 [1] CRAN (R 4.1.2)
 stringr   * 1.4.1   2022-08-20 [1] CRAN (R 4.1.2)
 TBDBr     * 0.1.0   2022-09-03 [1] Github (Talkbank/TBDBr@f88caca)
 tibble    * 3.1.8   2022-07-22 [1] CRAN (R 4.1.2)
 tidyr     * 1.2.1   2022-09-08 [1] CRAN (R 4.1.2)
 tidyverse * 1.3.2   2022-07-18 [1] CRAN (R 4.1.2)

 [1] /Users/francojc/R/Library
 [2] /Library/Frameworks/R.framework/Versions/4.1/Resources/library

```

**Comment by macw** [comment]
Jerid,
     This is the first posting of an issue to TBDBr and I’m not yet used to replying, but maybe this reply will work.  From your example, I’m not quite sure what the issue is.  Is it just the missing caption/label on the table?

— Brian MacWhinney

**Comment by rbcavanaugh** [comment]
@francojc I can reproduce your example. Can you try the following to see if it fixes your issue after loading TBDBr. kableExtra converts to HTML directly whereas the default I think prints md which is converted by pandoc...

```
iris |> 
    slice_head(n = 10) |> 
    knitr::kable(format = "markdown")
```

**Comment by francojc** [comment]
@rbcavanaugh That worked on the table format --which is great. 

There's still a problem with the quarto yaml `tbl-cap:` actually being added to the table. It appears as `?(caption)`. Might you know what this issue is here?

**Comment by rbcavanaugh** [comment]
Looks like a typo? The table without out a caption comes from a chunk with: 

#| tab-cap: 'Bad table.'

I haven't messed around with quarto much but when I run the document you provided, I don't get the automatic "Table 1:" headers - but that's consistent for before and after loading kableExtra - not sure if that's part of your question.

**Comment by francojc** [comment]
@rbcavanaugh You are right. I had a typo! Now the caption works just fine. 

Also I would like to note that I found another workaround to avoid having `kableExtra` apply the HTML styling is to add  `options(kableExtra.auto_format = FALSE)` before `kableExtra` gets loaded. Then there is no need to specify in the `kable()` function the format as markdown. 

Thanks for all your help!
