### ISSUE TITLE
Will all `get*()` functions have data to pull from the database?

### ISSUE THREAD

**Issue by francojc** [TalkBank/TBDBr#3]
I'm wondering if all TalkBank databases will have data for [all the `get*()` query functions](https://talkbank.github.io/TBDBr/articles/example-queries.html). 

For example, I've been able to retrieve various datasets from the CABNC: 

- `getUtterances()`
- `getTranscripts()`
- `getParticipants()`

But I'm not getting a data from `getTokens()` or `getTokenTypes()` --- hangs on "Fetching data, please wait...".

If not, is there a way to find out other than trying and waiting to see if the query returns a response?

Thanks,

**Comment by rbcavanaugh** [comment]
I'm not sure but I can try and trouble shoot next week. In the meantime you can always look at https://talkbank.org/DB/ to see if there is data that matches the query you're using.

**Comment by francojc** [comment]
https://talkbank.org/DB/ is just what I needed. Sorry for not closing this earlier.
